export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_NEW_PRODUCTS = "GET_NEW_PRODUCTS";
export const NEXT_CATALOG_PAGE = "NEXT_CATALOG_PAGE";
export const PREV_CATALOG_PAGE = "PREV_CATALOG_PAGE";
export const SEARCHING_OR_FILTERING_PRODUCTS = "SEARCHING_OR_FILTERING_PRODUCTS";
export const GET_TAGS = "GET_TAGS";
export const GET_MANUFACTURERS = "GET_MANUFACTURERS";
export const END_LOADING = "END_LOADING";